#!/usr/bin/env node
/**
 * Discovers product photos on disk so adding images needs no code changes:
 *   drop files into assets/images/<product-id>/  (1.jpg, 2.jpg, … or any name)
 *   run `npm run build`  →  assets/data/catalog-images.js
 * Only folders whose name matches a catalog id are picked up.
 */
const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const IMG_DIR = path.join(ROOT, 'assets/images');
const OUT = path.join(ROOT, 'assets/data/catalog-images.js');
const EXT = /\.(jpe?g|png|webp|avif)$/i;

function naturalSort(a, b) {
    return a.localeCompare(b, undefined, { numeric: true, sensitivity: 'base' });
}

/** @returns {Object<string,string[]>} id → root-absolute image paths */
function discover(ids, imgDir) {
    const dir = imgDir || IMG_DIR;
    const wanted = new Set(ids);
    const map = {};
    if (!fs.existsSync(dir)) return map;
    for (const name of fs.readdirSync(dir)) {
        if (!wanted.has(name)) continue;
        const full = path.join(dir, name);
        if (!fs.statSync(full).isDirectory()) continue;
        const files = fs.readdirSync(full).filter(f => EXT.test(f)).sort(naturalSort);
        if (files.length) map[name] = files.map(f => '/assets/images/' + name + '/' + f);
    }
    return map;
}

function render(map) {
    return '// AUTO-GENERATED by scripts/build-images.js — do not edit. Add photos under assets/images/<id>/ and run `npm run build`.\n' +
        'const CATALOG_IMAGES = ' + JSON.stringify(map, null, 2) + ';\n' +
        "if (typeof module !== 'undefined') module.exports = { CATALOG_IMAGES };\nelse window.CATALOG_IMAGES = CATALOG_IMAGES;\n";
}

if (require.main === module) {
    const { CATALOG_ITEMS } = require('../assets/data/catalog-items.js');
    const legacySrc = fs.readFileSync(path.join(ROOT, 'assets/js/products.js'), 'utf8');
    const legacy = new Function(legacySrc.replace('window.products = products;', 'return products;'))();
    const ids = CATALOG_ITEMS.map(p => p.id).concat(legacy.map(p => p.id));
    const map = discover(ids);
    fs.writeFileSync(OUT, render(map));
    console.log(`✓ assets/data/catalog-images.js — ${Object.keys(map).length} products with photo folders`);
}

module.exports = { discover, render };
